### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by alex-tee** [UtoECat/jack_utils#8]
Is this GPL-3.0 only or GPL-3.0 or later? Please clarify this (preferably in the headers by using the standard texts). Right now it just says: `This Program is free software. Licensed Under GNU GPL 3.0.`

**Comment by UtoECat** [comment]
Fixed in development branch. Changes will not get into the main branch soon, as there is still a lot of work to be done...
In any case, thanks :)

**Comment by alex-tee** [comment]
thanks!
